Note importance of using https url instead of http
Otherwise, the user will get this error:

`AttributeError: 'list' object has no attribute 'iteritems'`

which is rather difficult to track down.

Change-Id: I49f69bb34e38f7dda0e37fad7f50f11c07b71880